export const database = [
  {
    id: 1,
    optionType: "trigger",
    title: "Action is Performed",
    shortDesc: "Triggers when somebody visits a specified page",
    icon: "Eye",
  },
  {
    id: 2,
    optionType: "trigger",
    title: "New Visitor",
    shortDesc: "Triggers when somebody performs a specified action",
    icon: "Zap",
  },
  {
    id: 3,
    optionType: "trigger",
    title: "Time Has Passed",
    shortDesc: "Triggers after a specified amount of time",
    icon: "Clock",
  },
  {
    id: 4,
    optionType: "trigger",
    title: "Error Prompt",
    shortDesc: "Triggers when a specified error happens",
    icon: "Alert",
  },
  {
    id: 5,
    optionType: "action",
    title: "New Database Entry",
    shortDesc: "Adds a new entry to a specified database",
    icon: "Database",
  },
  {
    id: 6,
    optionType: "action",
    title: "Update Database",
    shortDesc: "Edits and deletes database entries and properities",
    icon: "Database",
  },
  {
    id: 7,
    optionType: "action",
    title: "Perform an Action",
    shortDesc: "Performs or edits a specified action",
    icon: "Zap",
  },
  {
    id: 8,
    optionType: "logger",
    title: "Add New Log Entry",
    shortDesc: "Adds a new log entry to this project",
    icon: "Terminal",
  },
  {
    id: 9,
    optionType: "logger",
    title: "Update Logs",
    shortDesc: "Edits and deletes log entries in this project",
    icon: "Terminal",
  },
  {
    id: 10,
    optionType: "logger",
    title: "Prompt an Error",
    shortDesc: "Triggers a specified error",
    icon: "Alert",
  },
];