export const database = [
  {
    id: 1,
    optionType: "trigger",
    title: "New Caller",
    shortDesc: "Triggers for a New Call",
    icon: "PhoneIncoming",
    noun: "Caller",
    conditionalOptions: [
      {
        question: "Location of Call",
        answer: ["Washington DC", "Baltimore", "Annapolis"],
      },
      {
        question: "Reason For Call",
        answer: [
          "New Issue",
          "Get Instructions",
          "Appointment",
          "Get Referral",
        ],
      },
      {
        question: "GP or Practice",
        answer: [
          "Washington DC Family Practice",
          "Cline and Smith GP",
          "Ivy and Towes",
          "H St Practice",
          "Rhode Island Associates",
        ],
      },
    ],
  },
  {
    id: 2,
    optionType: "trigger",
    title: "Action is Performed",
    shortDesc: "Trigger for Custom Action",
    icon: "Zap",
    noun: "Action",
    conditionalOptions: [],
  },
  {
    id: 3,
    optionType: "trigger",
    title: "New Medical Issue",
    shortDesc: "Triggers for New Medical Issue",
    icon: "Zap",
    noun: "Issue",
    conditionalOptions: [
      {
        question: "Life-Threatening",
        answer: ["Yes", "No"],
      },
    ],
  },
  {
    id: 4,
    optionType: "trigger",
    title: "Time Has Passed",
    shortDesc: "Triggers after a specified amount of time",
    icon: "Clock",
    noun: "Time",
    conditionalOptions: [],
  },
  {
    id: 5,
    optionType: "trigger",
    title: "New Event",
    shortDesc: "Triggers when an event occurs",
    icon: "Calendar",
    noun: "Event",
    conditionalOptions: [],
  },
  {
    id: 6,
    optionType: "trigger",
    title: "Error Prompt",
    shortDesc: "Triggers when a specified error happens",
    icon: "Alert",
    noun: "Error",
    conditionalOptions: [],
  },
  {
    id: 21,
    optionType: "action",
    title: "New Database Entry",
    shortDesc: "Adds a new entry to a specified database",
    icon: "Database",
    noun: "Database",
    conditionalOptions: [],
  },
  {
    id: 22,
    optionType: "action",
    title: "Update Database",
    shortDesc: "Edits and deletes database entries and properities",
    icon: "Database",
    noun: "Database",
    conditionalOptions: [],
  },
  {
    id: 22,
    optionType: "action",
    title: "Create New Event",
    shortDesc: "Creates a New Event",
    icon: "Calendar",
    noun: "Event",
    conditionalOptions: [],
  },
  {
    id: 23,
    optionType: "action",
    title: "Perform Custom Action",
    shortDesc: "Performs or edits a specified action",
    icon: "Zap",
    noun: "Action",
    conditionalOptions: [],
  },
  {
    id: 41,
    optionType: "logger",
    title: "Add New Entry To Patient Log",
    shortDesc: "Adds a new log entry to this project",
    icon: "Terminal",
    noun: "Entry",
    conditionalOptions: [],
  },
  {
    id: 42,
    optionType: "logger",
    title: "Update Patient Log",
    shortDesc: "Edits and deletes log entries in this project",
    icon: "Terminal",
    noun: "Entry",
    conditionalOptions: [],
  },
  {
    id: 43,
    optionType: "logger",
    title: "Prompt an Error",
    shortDesc: "Triggers a specified error",
    icon: "Alert",
    noun: "Error",
    conditionalOptions: [
      {
        option: "Which Database",
      },
    ],
  },
];
